config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
    belongs_to :question

    validates :name, :presence => true
    validates :answer, :presence => true
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  validates :name, :presence => true
  validates :question, :presence => true
  end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    def new
      @question = Question.find(params[:question_id])
      @answer = @question.answers.new
    end
    def create
      @question = Question.find(params[:question_id])
      @answer = @question.answers.new(answer_params)
      if @answer.save
        redirect_to question_path(@answer.question)
      else
        render :new
      end
    end

  private
    def answer_params
      params.require(:answer).permit(:name, :answer)
    end

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
      @questions = Question.all
      render :index
  end
  def show
      @question = Question.find(params[:id])
      render :show
  end
  def new
      @question = Question.new
      render :new
    end
  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to  questions_path
    else
      render :new
    end
  end
  private
    def question_params
      params.require(:question).permit(:name, :question)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/new.html.erb
<%= form_for [@question, @answer] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :answer %>
    <%= f.text_field :answer %>
    <p><%= f.submit %></p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackOverflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<h2>Questions</h2>
<%= link_to "New Question", new_question_path %>
<hr>
<ul>
    <% @questions.each do |question| %>
      <li><%= link_to question.question, question_path(question) %> by <%= question.name%></li><br><hr><br>
    <% end %>
  </ul>

app/views/questions/new.html.erb
<h1>Ask a Question</h1>

<% if @question.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% @question.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <%= form_for @question do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :question %>
    <%= f.text_field :question %>
    <%= f.submit  %>
  <% end %>

app/views/questions/show.html.erb
<h1><%= @question.question %></h1>

  <p><%= link_to "Return to questions", questions_path %></p>
  <p><%= link_to "New Answer", new_question_answer_path(@question, @answer) %></p>

<% if @question.answers.any? %>

    <ul>
      <% @question.answers.each do |answer| %>
        <li>
          <%= answer.answer %> by <%= answer.name%><br>
        </li><br> <hr>
      <% end %>
    </ul>
  <% else %>
    <p>There are no answers currently</p>
  <% end %>